=== Politecnicojic2022-01/Ejercicio5/ListaCompras.dtd
<!ELEMENT ListaCompras (Venta)+>
        <!ELEMENT Venta (VentaCredito?, VentaInmediata?)>
        <!ELEMENT VentaCredito (FechaFinPago?,Cantidad)>
        <!ELEMENT VentaInmediata (cantidad, divisa)>
        <!ELEMENT Cantidad (#PCDATA) >
        <!ELEMENT FechaFinPago (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA) >
        <!ELEMENT divisa (#PCDATA) >

=== Politecnicojic2022-01/Ejercicio5/ListaCompras.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ListaCompras SYSTEM "ListaCompras.dtd">
<ListaCompras>
    <Venta>
        <VentaCredito>
            <FechaFinPago></FechaFinPago>
            <Cantidad></Cantidad>
        </VentaCredito>
        <VentaInmediata>
            <cantidad></cantidad>
            <divisa></divisa>
        </VentaInmediata>
    </Venta>
</ListaCompras>
